//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Net.Http {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Net.Http.Net.Http.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified file length was too large for the file system..
        /// </summary>
        public static string ArgumentOutOfRange_FileLengthTooBig {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_FileLengthTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-negative number required..
        /// </summary>
        public static string ArgumentOutOfRange_NeedNonNegativeNum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedNonNegativeNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive number required..
        /// </summary>
        public static string ArgumentOutOfRange_NeedPosNum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedPosNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned {1}..
        /// </summary>
        public static string event_OperationReturnedSomething {
            get {
                return ResourceManager.GetString("event_OperationReturnedSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid character was found in header name..
        /// </summary>
        public static string InvalidHeaderName {
            get {
                return ResourceManager.GetString("InvalidHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; already exists..
        /// </summary>
        public static string IO_FileExists_Name {
            get {
                return ResourceManager.GetString("IO_FileExists_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the specified file..
        /// </summary>
        public static string IO_FileNotFound {
            get {
                return ResourceManager.GetString("IO_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file &apos;{0}&apos;..
        /// </summary>
        public static string IO_FileNotFound_FileName {
            get {
                return ResourceManager.GetString("IO_FileNotFound_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a part of the path..
        /// </summary>
        public static string IO_PathNotFound_NoPathName {
            get {
                return ResourceManager.GetString("IO_PathNotFound_NoPathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a part of the path &apos;{0}&apos;..
        /// </summary>
        public static string IO_PathNotFound_Path {
            get {
                return ResourceManager.GetString("IO_PathNotFound_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file name or path is too long, or a component of the specified path is too long..
        /// </summary>
        public static string IO_PathTooLong {
            get {
                return ResourceManager.GetString("IO_PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path &apos;{0}&apos; is too long, or a component of the specified path is too long..
        /// </summary>
        public static string IO_PathTooLong_Path {
            get {
                return ResourceManager.GetString("IO_PathTooLong_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to move the position before the beginning of the stream..
        /// </summary>
        public static string IO_SeekBeforeBegin {
            get {
                return ResourceManager.GetString("IO_SeekBeforeBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process cannot access the file &apos;{0}&apos; because it is being used by another process..
        /// </summary>
        public static string IO_SharingViolation_File {
            get {
                return ResourceManager.GetString("IO_SharingViolation_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process cannot access the file because it is being used by another process..
        /// </summary>
        public static string IO_SharingViolation_NoFileName {
            get {
                return ResourceManager.GetString("IO_SharingViolation_NoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified string is not in the form required for an e-mail address..
        /// </summary>
        public static string MailAddressInvalidFormat {
            get {
                return ResourceManager.GetString("MailAddressInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid character was found in the mail header: &apos;{0}&apos;..
        /// </summary>
        public static string MailHeaderFieldInvalidCharacter {
            get {
                return ResourceManager.GetString("MailHeaderFieldInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mail header is malformed..
        /// </summary>
        public static string MailHeaderFieldMalformedHeader {
            get {
                return ResourceManager.GetString("MailHeaderFieldMalformedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol error: A received message contains a valid signature but it was not encrypted as required by the effective Protection Level..
        /// </summary>
        public static string net_auth_message_not_encrypted {
            get {
                return ResourceManager.GetString("net_auth_message_not_encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be performed on a completed asynchronous result object..
        /// </summary>
        public static string net_completed_result {
            get {
                return ResourceManager.GetString("net_completed_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient buffer space. Required: {0} Actual: {1}..
        /// </summary>
        public static string net_context_buffer_too_small {
            get {
                return ResourceManager.GetString("net_context_buffer_too_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos;=&apos;{1}&apos; part of the cookie is invalid..
        /// </summary>
        public static string net_cookie_attribute {
            get {
                return ResourceManager.GetString("net_cookie_attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSSAPI operation failed with status: {0} (Minor status: {1})..
        /// </summary>
        public static string net_gssapi_operation_failed {
            get {
                return ResourceManager.GetString("net_gssapi_operation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSSAPI operation failed with error - {0} ({1})..
        /// </summary>
        public static string net_gssapi_operation_failed_detailed {
            get {
                return ResourceManager.GetString("net_gssapi_operation_failed_detailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null or empty..
        /// </summary>
        public static string net_http_argument_empty_string {
            get {
                return ResourceManager.GetString("net_http_argument_empty_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed because the connection could not be reused..
        /// </summary>
        public static string net_http_authconnectionfailure {
            get {
                return ResourceManager.GetString("net_http_authconnectionfailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer was not long enough..
        /// </summary>
        public static string net_http_buffer_insufficient_length {
            get {
                return ResourceManager.GetString("net_http_buffer_insufficient_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Transfer-Encoding: chunked&apos; header can not be used when content object is not specified..
        /// </summary>
        public static string net_http_chunked_not_allowed_with_empty_content {
            get {
                return ResourceManager.GetString("net_http_chunked_not_allowed_with_empty_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base address must be an absolute URI..
        /// </summary>
        public static string net_http_client_absolute_baseaddress_required {
            get {
                return ResourceManager.GetString("net_http_client_absolute_baseaddress_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending the request..
        /// </summary>
        public static string net_http_client_execution_error {
            get {
                return ResourceManager.GetString("net_http_client_execution_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only &apos;http&apos; and &apos;https&apos; schemes are allowed..
        /// </summary>
        public static string net_http_client_http_baseaddress_required {
            get {
                return ResourceManager.GetString("net_http_client_http_baseaddress_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set..
        /// </summary>
        public static string net_http_client_invalid_requesturi {
            get {
                return ResourceManager.GetString("net_http_client_invalid_requesturi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request message was already sent. Cannot send the same request message multiple times..
        /// </summary>
        public static string net_http_client_request_already_sent {
            get {
                return ResourceManager.GetString("net_http_client_request_already_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write more bytes to the buffer than the configured maximum buffer size: {0}..
        /// </summary>
        public static string net_http_content_buffersize_exceeded {
            get {
                return ResourceManager.GetString("net_http_content_buffersize_exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffering more than {0} bytes is not supported..
        /// </summary>
        public static string net_http_content_buffersize_limit {
            get {
                return ResourceManager.GetString("net_http_content_buffersize_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field cannot be longer than {0} characters..
        /// </summary>
        public static string net_http_content_field_too_long {
            get {
                return ResourceManager.GetString("net_http_content_field_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set..
        /// </summary>
        public static string net_http_content_invalid_charset {
            get {
                return ResourceManager.GetString("net_http_content_invalid_charset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream does not support concurrent read operations..
        /// </summary>
        public static string net_http_content_no_concurrent_reads {
            get {
                return ResourceManager.GetString("net_http_content_no_concurrent_reads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The async operation did not return a System.Threading.Tasks.Task object..
        /// </summary>
        public static string net_http_content_no_task_returned {
            get {
                return ResourceManager.GetString("net_http_content_no_task_returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream does not support writing..
        /// </summary>
        public static string net_http_content_readonly_stream {
            get {
                return ResourceManager.GetString("net_http_content_readonly_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream was already consumed. It cannot be read again..
        /// </summary>
        public static string net_http_content_stream_already_read {
            get {
                return ResourceManager.GetString("net_http_content_stream_already_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while copying content to a stream..
        /// </summary>
        public static string net_http_content_stream_copy_error {
            get {
                return ResourceManager.GetString("net_http_content_stream_copy_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of elements is greater than the available space from arrayIndex to the end of the destination array..
        /// </summary>
        public static string net_http_copyto_array_too_small {
            get {
                return ResourceManager.GetString("net_http_copyto_array_too_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using this feature requires Windows 10 Version 1607..
        /// </summary>
        public static string net_http_feature_requires_Windows10Version1607 {
            get {
                return ResourceManager.GetString("net_http_feature_requires_Windows10Version1607", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client certificate was not found in the personal (\&quot;MY\&quot;) certificate store. In UWP, client certificates are only supported if they have been added to that certificate store..
        /// </summary>
        public static string net_http_feature_UWPClientCertSupportRequiresCertInPersonalCertificateStore {
            get {
                return ResourceManager.GetString("net_http_feature_UWPClientCertSupportRequiresCertInPersonalCertificateStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request message must be provided. It cannot be null..
        /// </summary>
        public static string net_http_handler_norequest {
            get {
                return ResourceManager.GetString("net_http_handler_norequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler did not return a response message..
        /// </summary>
        public static string net_http_handler_noresponse {
            get {
                return ResourceManager.GetString("net_http_handler_noresponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inner handler has not been assigned..
        /// </summary>
        public static string net_http_handler_not_assigned {
            get {
                return ResourceManager.GetString("net_http_handler_not_assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value is not a valid quoted string..
        /// </summary>
        public static string net_http_headers_invalid_etag_name {
            get {
                return ResourceManager.GetString("net_http_headers_invalid_etag_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value is not a valid &apos;From&apos; header string..
        /// </summary>
        public static string net_http_headers_invalid_from_header {
            get {
                return ResourceManager.GetString("net_http_headers_invalid_from_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The header name format is invalid..
        /// </summary>
        public static string net_http_headers_invalid_header_name {
            get {
                return ResourceManager.GetString("net_http_headers_invalid_header_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value is not a valid &apos;Host&apos; header string..
        /// </summary>
        public static string net_http_headers_invalid_host_header {
            get {
                return ResourceManager.GetString("net_http_headers_invalid_host_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid range. At least one of the two parameters must not be null..
        /// </summary>
        public static string net_http_headers_invalid_range {
            get {
                return ResourceManager.GetString("net_http_headers_invalid_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of value &apos;{0}&apos; is invalid..
        /// </summary>
        public static string net_http_headers_invalid_value {
            get {
                return ResourceManager.GetString("net_http_headers_invalid_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-line characters in header values must be followed by a white-space character..
        /// </summary>
        public static string net_http_headers_no_newlines {
            get {
                return ResourceManager.GetString("net_http_headers_no_newlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects..
        /// </summary>
        public static string net_http_headers_not_allowed_header_name {
            get {
                return ResourceManager.GetString("net_http_headers_not_allowed_header_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given header was not found..
        /// </summary>
        public static string net_http_headers_not_found {
            get {
                return ResourceManager.GetString("net_http_headers_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add value because header &apos;{0}&apos; does not support multiple values..
        /// </summary>
        public static string net_http_headers_single_value_header {
            get {
                return ResourceManager.GetString("net_http_headers_single_value_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the HTTP method is invalid..
        /// </summary>
        public static string net_http_httpmethod_format_error {
            get {
                return ResourceManager.GetString("net_http_httpmethod_format_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP method &apos;{0}&apos; is not supported on this platform..
        /// </summary>
        public static string net_http_httpmethod_notsupported_error {
            get {
                return ResourceManager.GetString("net_http_httpmethod_notsupported_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using CookieUsePolicy.UseSpecifiedCookieContainer, the CookieContainer property must not be null..
        /// </summary>
        public static string net_http_invalid_cookiecontainer {
            get {
                return ResourceManager.GetString("net_http_invalid_cookiecontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} property must be set to &apos;{1}&apos; to use this property..
        /// </summary>
        public static string net_http_invalid_enable_first {
            get {
                return ResourceManager.GetString("net_http_invalid_enable_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using WindowsProxyUsePolicy.UseCustomProxy, the Proxy property must not be null..
        /// </summary>
        public static string net_http_invalid_proxy {
            get {
                return ResourceManager.GetString("net_http_invalid_proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the &apos;http&apos; scheme is allowed for proxies..
        /// </summary>
        public static string net_http_invalid_proxy_scheme {
            get {
                return ResourceManager.GetString("net_http_invalid_proxy_scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using a non-null Proxy, the WindowsProxyUsePolicy property must be set to WindowsProxyUsePolicy.UseCustomProxy..
        /// </summary>
        public static string net_http_invalid_proxyusepolicy {
            get {
                return ResourceManager.GetString("net_http_invalid_proxyusepolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned an invalid or unrecognized response..
        /// </summary>
        public static string net_http_invalid_response {
            get {
                return ResourceManager.GetString("net_http_invalid_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The read operation failed, see inner exception..
        /// </summary>
        public static string net_http_io_read {
            get {
                return ResourceManager.GetString("net_http_io_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read data from the transport connection. The connection was closed before all data could be read. Expected {0} bytes, read {1} bytes..
        /// </summary>
        public static string net_http_io_read_incomplete {
            get {
                return ResourceManager.GetString("net_http_io_read_incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The write operation failed, see inner exception..
        /// </summary>
        public static string net_http_io_write {
            get {
                return ResourceManager.GetString("net_http_io_write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handler does not support custom handling of certificates on this operating system. Consider using System.Net.Http.SocketsHttpHandler..
        /// </summary>
        public static string net_http_libcurl_callback_notsupported_os {
            get {
                return ResourceManager.GetString("net_http_libcurl_callback_notsupported_os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handler does not support custom handling of certificates with this combination of libcurl ({0}) and its SSL backend (&quot;{1}&quot;). An SSL backend based on &quot;{2}&quot; is required. Consider using System.Net.Http.SocketsHttpHandler..
        /// </summary>
        public static string net_http_libcurl_callback_notsupported_sslbackend {
            get {
                return ResourceManager.GetString("net_http_libcurl_callback_notsupported_sslbackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handler does not support client authentication certificates on this operating system. Consider using System.Net.Http.SocketsHttpHandler..
        /// </summary>
        public static string net_http_libcurl_clientcerts_notsupported_os {
            get {
                return ResourceManager.GetString("net_http_libcurl_clientcerts_notsupported_os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handler does not support client authentication certificates with this combination of libcurl ({0}) and its SSL backend (&quot;{1}&quot;). An SSL backend based on &quot;{2}&quot; is required. Consider using System.Net.Http.SocketsHttpHandler..
        /// </summary>
        public static string net_http_libcurl_clientcerts_notsupported_sslbackend {
            get {
                return ResourceManager.GetString("net_http_libcurl_clientcerts_notsupported_sslbackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handler does not support changing revocation settings with this combination of libcurl ({0}) and its SSL backend (&quot;{1}&quot;). An SSL backend based on &quot;{2}&quot; is required. Consider using System.Net.Http.SocketsHttpHandler..
        /// </summary>
        public static string net_http_libcurl_revocation_notsupported_sslbackend {
            get {
                return ResourceManager.GetString("net_http_libcurl_revocation_notsupported_sslbackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;q&apos; value is invalid: &apos;{0}&apos;..
        /// </summary>
        public static string net_http_log_headers_invalid_quality {
            get {
                return ResourceManager.GetString("net_http_log_headers_invalid_quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for header &apos;{0}&apos; contains invalid new-line characters. Value: &apos;{1}&apos;..
        /// </summary>
        public static string net_http_log_headers_no_newlines {
            get {
                return ResourceManager.GetString("net_http_log_headers_no_newlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; is not a valid email address. Error: {1}.
        /// </summary>
        public static string net_http_log_headers_wrong_email_format {
            get {
                return ResourceManager.GetString("net_http_log_headers_wrong_email_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response status code does not indicate success: {0} ({1})..
        /// </summary>
        public static string net_http_message_not_success_statuscode {
            get {
                return ResourceManager.GetString("net_http_message_not_success_statuscode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream does not support concurrent I/O read or write operations..
        /// </summary>
        public static string net_http_no_concurrent_io_allowed {
            get {
                return ResourceManager.GetString("net_http_no_concurrent_io_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance has already started one or more requests. Properties can only be modified before sending the first request..
        /// </summary>
        public static string net_http_operation_started {
            get {
                return ResourceManager.GetString("net_http_operation_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; is not a valid Base64 string. Error: {1}.
        /// </summary>
        public static string net_http_parser_invalid_base64_string {
            get {
                return ResourceManager.GetString("net_http_parser_invalid_base64_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reason phrase must not contain new-line characters..
        /// </summary>
        public static string net_http_reasonphrase_format_error {
            get {
                return ResourceManager.GetString("net_http_reasonphrase_format_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request headers must contain only ASCII characters..
        /// </summary>
        public static string net_http_request_invalid_char_encoding {
            get {
                return ResourceManager.GetString("net_http_request_invalid_char_encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECT request must contain Host header..
        /// </summary>
        public static string net_http_request_no_host {
            get {
                return ResourceManager.GetString("net_http_request_no_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP response headers length exceeded the set limit of {0} bytes..
        /// </summary>
        public static string net_http_response_headers_exceeded_length {
            get {
                return ResourceManager.GetString("net_http_response_headers_exceeded_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SSL connection could not be established, see inner exception..
        /// </summary>
        public static string net_http_ssl_connection_failed {
            get {
                return ResourceManager.GetString("net_http_ssl_connection_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handler was disposed of while active operations were in progress..
        /// </summary>
        public static string net_http_unix_handler_disposed {
            get {
                return ResourceManager.GetString("net_http_unix_handler_disposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The libcurl library in use ({0}) does not support HTTPS..
        /// </summary>
        public static string net_http_unix_https_support_unavailable_libcurl {
            get {
                return ResourceManager.GetString("net_http_unix_https_support_unavailable_libcurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The libcurl library in use ({0}) does not support different credentials for different authentication schemes..
        /// </summary>
        public static string net_http_unix_invalid_credential {
            get {
                return ResourceManager.GetString("net_http_unix_invalid_credential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP 1.0 does not support chunking..
        /// </summary>
        public static string net_http_unsupported_chunking {
            get {
                return ResourceManager.GetString("net_http_unsupported_chunking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request HttpVersion 0.X is not supported.  Use 1.0 or above..
        /// </summary>
        public static string net_http_unsupported_version {
            get {
                return ResourceManager.GetString("net_http_unsupported_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username for a credential object cannot be null or empty..
        /// </summary>
        public static string net_http_username_empty_string {
            get {
                return ResourceManager.GetString("net_http_username_empty_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value must be greater than {0}..
        /// </summary>
        public static string net_http_value_must_be_greater_than {
            get {
                return ResourceManager.GetString("net_http_value_must_be_greater_than", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not supported for property &apos;{1}&apos;..
        /// </summary>
        public static string net_http_value_not_supported {
            get {
                return ResourceManager.GetString("net_http_value_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} calling {1}, &apos;{2}&apos;..
        /// </summary>
        public static string net_http_winhttp_error {
            get {
                return ResourceManager.GetString("net_http_winhttp_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value is not valid in the &apos;{0}&apos; enumeration..
        /// </summary>
        public static string net_invalid_enum {
            get {
                return ResourceManager.GetString("net_invalid_enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed with error {1}..
        /// </summary>
        public static string net_log_operation_failed_with_error {
            get {
                return ResourceManager.GetString("net_log_operation_failed_with_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is not implemented by this class..
        /// </summary>
        public static string net_MethodNotImplementedException {
            get {
                return ResourceManager.GetString("net_MethodNotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No support for channel binding on operating systems other than Windows..
        /// </summary>
        public static string net_nego_channel_binding_not_supported {
            get {
                return ResourceManager.GetString("net_nego_channel_binding_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target name should be non empty if default credentials are passed..
        /// </summary>
        public static string net_nego_not_supported_empty_target_with_defaultcreds {
            get {
                return ResourceManager.GetString("net_nego_not_supported_empty_target_with_defaultcreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested protection level is not supported with the gssapi implementation currently installed..
        /// </summary>
        public static string net_nego_protection_level_not_supported {
            get {
                return ResourceManager.GetString("net_nego_protection_level_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server implementation is not supported.
        /// </summary>
        public static string net_nego_server_not_supported {
            get {
                return ResourceManager.GetString("net_nego_server_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTLM authentication is not possible with default credentials on this platform..
        /// </summary>
        public static string net_ntlm_not_possible_default_cred {
            get {
                return ResourceManager.GetString("net_ntlm_not_possible_default_cred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested security package is not supported..
        /// </summary>
        public static string net_securitypackagesupport {
            get {
                return ResourceManager.GetString("net_securitypackagesupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested security protocol is not supported..
        /// </summary>
        public static string net_securityprotocolnotsupported {
            get {
                return ResourceManager.GetString("net_securityprotocolnotsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application protocol list is invalid..
        /// </summary>
        public static string net_ssl_app_protocols_invalid {
            get {
                return ResourceManager.GetString("net_ssl_app_protocols_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support reading..
        /// </summary>
        public static string NotSupported_UnreadableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnreadableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support writing..
        /// </summary>
        public static string NotSupported_UnwritableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnwritableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not access a closed Stream..
        /// </summary>
        public static string ObjectDisposed_StreamClosed {
            get {
                return ResourceManager.GetString("ObjectDisposed_StreamClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a supported handle type..
        /// </summary>
        public static string SSPIInvalidHandleType {
            get {
                return ResourceManager.GetString("SSPIInvalidHandleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the path is denied..
        /// </summary>
        public static string UnauthorizedAccess_IODenied_NoPathName {
            get {
                return ResourceManager.GetString("UnauthorizedAccess_IODenied_NoPathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the path &apos;{0}&apos; is denied..
        /// </summary>
        public static string UnauthorizedAccess_IODenied_Path {
            get {
                return ResourceManager.GetString("UnauthorizedAccess_IODenied_Path", resourceCulture);
            }
        }
    }
}
